//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dampferstube.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class aroman
    {
        public int ID { get; set; }
        public string Aroma_name { get; set; }
        public string Aroma_desc { get; set; }
        public Nullable<int> Hersteller { get; set; }
        public Nullable<int> Kategorie { get; set; }
        public Nullable<int> Besitzer { get; set; }
        public Nullable<int> Rating { get; set; }
    
        public virtual Besitzer Besitzer1 { get; set; }
        public virtual Hersteller Hersteller1 { get; set; }
        public virtual Kategorie Kategorie1 { get; set; }
    }
}
