//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dampferstube.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Besitzer
    {
        public Besitzer()
        {
            this.aromen = new HashSet<aroman>();
        }
    
        public int ID { get; set; }
        public string Vorname { get; set; }
        public string Nachname { get; set; }
    
        public virtual ICollection<aroman> aromen { get; set; }
    }
}
