//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dampferstube.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DampferstubeEntities : DbContext
    {
        public DampferstubeEntities()
            : base("name=DampferstubeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<aroman> aromen { get; set; }
        public virtual DbSet<Besitzer> Besitzers { get; set; }
        public virtual DbSet<Hersteller> Herstellers { get; set; }
        public virtual DbSet<Kategorie> Kategories { get; set; }
    }
}
