//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dampferstube.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hersteller
    {
        public Hersteller()
        {
            this.aromen = new HashSet<aroman>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Webseite { get; set; }
        public string Land { get; set; }
        public Nullable<bool> Zertifikat { get; set; }
    
        public virtual ICollection<aroman> aromen { get; set; }
    }
}
